# Generated by Django 5.0.6 on 2026-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Can this user access the seller dashboard?'),
        ),
    ]
