# Generated by Django 5.0.6 on 2026-06-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_requested',
            field=models.BooleanField(default=False, help_text='User has requested seller access, pending admin approval'),
        ),
    ]
