# Generated by Django 5.0.6 on 2026-06-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address_line1_profile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_rejection_reason',
            field=models.TextField(blank=True, help_text='If seller request was declined, why'),
        ),
    ]
