# Generated by Django 5.0.6 on 2026-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_seller_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual / Sole Proprietor'), ('company', 'Company / Business Entity')], help_text='Type of seller account', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_description',
            field=models.TextField(blank=True, help_text='Describe what you sell'),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, help_text='Your store/business name', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='store_slug',
            field=models.SlugField(blank=True, help_text='URL slug for your public store page', max_length=200),
        ),
    ]
