# Generated by Django 5.0.6 on 2026-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_business_type_profile_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_address',
            field=models.TextField(blank=True, help_text='Registered business address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_registration',
            field=models.CharField(blank=True, help_text='Business registration / license number', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_proof',
            field=models.ImageField(blank=True, help_text='Government ID or business license', null=True, upload_to='seller_docs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax ID / VAT number', max_length=200),
        ),
    ]
