# Generated by Django 5.0.6 on 2026-06-21 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_email_verified_profile_is_phone_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=20)),
                ('store_description', models.TextField(blank=True)),
                ('business_registration', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'credential histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
