# Generated by Django 5.0.6 on 2026-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_credential_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the user last requested seller access', null=True),
        ),
    ]
