# Generated by Django 5.0.6 on 2026-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_emoji',
            field=models.CharField(blank=True, default='🟢', help_text='Custom status emoji (e.g. 🟢, 🔴, 🌙, ⛔)', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_text',
            field=models.CharField(blank=True, default='Available', help_text='Custom status text (e.g. Available, Busy, At work, Away)', max_length=100),
        ),
    ]
