# Generated by Django 5.0.6 on 2026-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_status_emoji_profile_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='avatars/'),
        ),
    ]
