# Generated by Django 5.0.6 on 2026-06-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(blank=True, help_text='address', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(blank=True, help_text='apt/suite', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='photo', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_address',
            field=models.TextField(blank=True, help_text='business address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_registration',
            field=models.CharField(blank=True, help_text='license no', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual / Sole Proprietor'), ('company', 'Company / Business Entity')], help_text='account type', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_proof',
            field=models.ImageField(blank=True, help_text='gov ID', null=True, upload_to='seller_docs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='email verified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='phone verified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='seller access'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller_rejection_reason',
            field=models.TextField(blank=True, help_text='decline reason'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller_requested',
            field=models.BooleanField(default=False, help_text='seller requested'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller_requested_at',
            field=models.DateTimeField(blank=True, help_text='request date', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_emoji',
            field=models.CharField(blank=True, default='', help_text='Custom status emoji (e.g. , , , )', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_description',
            field=models.TextField(blank=True, help_text='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, help_text='store name', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_slug',
            field=models.SlugField(blank=True, help_text='store slug', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='tax ID', max_length=200),
        ),
    ]
