# Generated by Django 5.0.6 on 2026-06-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('hi', 'Hindi'), ('ko', 'Korean')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rtl', models.BooleanField(default=False, help_text='Right-to-left script')),
                ('flag_icon', models.CharField(blank=True, help_text='Emoji or icon code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier for this translation (e.g., 'home.title', 'cart.checkout')", max_length=255)),
                ('value', models.TextField(help_text='Translated text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.language')),
            ],
            options={
                'verbose_name_plural': 'Translations',
                'ordering': ['key'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
