# Generated by Django 5.0.6 on 2026-06-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Comma-separated sizes, e.g. S,M,L,XL or 5kg,10kg,20kg', max_length=100, null=True),
        ),
    ]
