# Generated by Django 5.0.6 on 2026-06-20 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cartitem_size_orderitem_size_productsize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('fav_add', 'Added to Favorites'), ('fav_remove', 'Removed from Favorites'), ('cart_add', 'Added to Cart'), ('cart_remove', 'Removed from Cart'), ('cart_update', 'Updated Cart Quantity'), ('order_place', 'Placed Order'), ('order_cancel', 'Cancelled Order'), ('order_status', 'Order Status Changed'), ('product_create', 'Created Product'), ('product_update', 'Updated Product'), ('product_delete', 'Deleted Product'), ('seller_apply', 'Applied as Seller'), ('seller_approve', 'Seller Approved'), ('seller_decline', 'Seller Declined'), ('seller_revoke', 'Seller Revoked'), ('user_register', 'User Registered'), ('review_add', 'Added Review'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
