# Generated by Django 5.0.6 on 2026-06-20 06:30

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models._UploadToPath('category_images')),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models._UploadToPath('products')),
        ),
    ]
