# Generated by Django 5.0.6 on 2026-06-20 06:37

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models._UploadToPath('products', subfolder_attr='category_id')),
        ),
    ]
