# Generated by Django 5.0.6 on 2026-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount. Leave blank if same as price.', max_digits=10, null=True),
        ),
    ]
