# Generated by Django 5.0.6 on 2026-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('fav_add', 'Added to Favorites'), ('fav_remove', 'Removed from Favorites'), ('cart_add', 'Added to Cart'), ('cart_remove', 'Removed from Cart'), ('cart_update', 'Updated Cart Quantity'), ('order_place', 'Placed Order'), ('order_cancel', 'Cancelled Order'), ('order_status', 'Order Status Changed'), ('product_create', 'Created Product'), ('product_update', 'Updated Product'), ('product_delete', 'Deleted Product'), ('seller_apply', 'Applied as Seller'), ('seller_approve', 'Seller Approved'), ('seller_decline', 'Seller Declined'), ('seller_revoke', 'Seller Revoked'), ('user_register', 'User Registered'), ('review_add', 'Added Review'), ('login', 'User Login'), ('logout', 'User Logout'), ('size_create', 'Size Created'), ('size_update', 'Size Updated'), ('size_delete', 'Size Deleted')], max_length=30),
        ),
    ]
