# Generated by Django 5.0.6 on 2026-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_size_activity_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this subscriber still active?'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='token',
            field=models.CharField(blank=True, help_text='Unique token for unsubscribe', max_length=64, null=True, unique=True),
        ),
    ]
