# Generated by Django 5.0.6 on 2026-06-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_newslettersubscriber_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('gold', 'Gold'), ('ocean', 'Ocean'), ('purple', 'Purple'), ('fifa', 'FIFA'), ('cricket', 'Cricket'), ('anime', 'Anime'), ('dev', 'Dev'), ('spiderman', 'Spiderman'), ('batman', 'Batman'), ('ironman', 'Iron Man'), ('naruto', 'Naruto'), ('goku', 'Goku'), ('onepiece', 'One Piece')], default='dark', max_length=20),
        ),
    ]
