# Generated by Django 5.0.6 on 2026-06-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_conversation_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='active',
            field=models.BooleanField(default=True, help_text='active'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='token',
            field=models.CharField(blank=True, help_text='unsubscribe token', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='original price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='seller', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='sizes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(help_text='e.g. S, M, L', max_length=50),
        ),
    ]
