# Generated by Django 5.0.6 on 2026-06-30 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_add_delivery_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sale'], name='store_produ_is_sale_461e37_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_a0ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='store_produ_rating_824be5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='store_produ_stock_3f6dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['original_price'], name='store_produ_origina_82e536_idx'),
        ),
    ]
